import React from 'react';
import { X, Copy, Check } from 'lucide-react';
import ReactMarkdown from 'react-markdown';

interface SummaryModalProps {
  isOpen: boolean;
  onClose: () => void;
  summary: string;
}

const SummaryModal: React.FC<SummaryModalProps> = ({ isOpen, onClose, summary }) => {
  const [copied, setCopied] = React.useState(false);

  if (!isOpen) return null;

  const handleCopy = () => {
    navigator.clipboard.writeText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-[60] flex items-center justify-center p-4 bg-black/20 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl max-h-[80vh] flex flex-col overflow-hidden border border-white/50">
        <div className="flex items-center justify-between p-4 border-b border-gray-100 bg-gray-50/50">
          <h2 className="text-lg font-semibold text-gray-800 flex items-center gap-2">
            <span className="text-xl">✨</span> AI Summary
          </h2>
          <div className="flex items-center gap-2">
             <button 
              onClick={handleCopy}
              className="p-2 hover:bg-gray-200/50 rounded-full transition-colors text-gray-500 hover:text-gray-700"
              title="Copy to clipboard"
            >
              {copied ? <Check size={18} className="text-green-500" /> : <Copy size={18} />}
            </button>
            <button 
              onClick={onClose}
              className="p-2 hover:bg-red-50 rounded-full transition-colors text-gray-400 hover:text-red-500"
            >
              <X size={20} />
            </button>
          </div>
        </div>
        
        <div className="flex-1 overflow-y-auto p-6 bg-white prose prose-sm max-w-none prose-headings:font-semibold prose-p:text-gray-600 prose-li:text-gray-600">
          <ReactMarkdown>{summary}</ReactMarkdown>
        </div>
        
        <div className="p-4 border-t border-gray-100 bg-gray-50/50 text-xs text-center text-gray-400">
          Generated by Gemini 2.5 Flash
        </div>
      </div>
    </div>
  );
};

export default SummaryModal;
